[build-system]
requires = ["setuptools_scm[toml]>=3.4.3", "setuptools-rust"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"
write_to = "py_tegra_swizzle/version.py"

[tool.cibuildwheel]
build-frontend = "build"